CREATE TABLE CODE_BOARD_MANAGER (
  SEQ number(11) NOT NULL,
  TITLE varchar2(100) NOT NULL,
  USE_F varchar2(1) NOT NULL,
  BLOG_F varchar2(1) NOT NULL,
  REG_DATE DATE NOT NULL,
  REG_USER_SEQ number(11) NOT NULL,
  MOD_DATE DATE DEFAULT NULL,
  MOD_USER_SEQ number(11) DEFAULT NULL,
  DEL_DATE DATE DEFAULT NULL,
  PRIMARY KEY (SEQ)  
);

CREATE SEQUENCE SEQ_BOARD_MANAGER
    start with 1
    increment by 1
    nomaxvalue
    nocycle;

CREATE TABLE CODE_BOARD_ARTICLE (
  SEQ number(11) NOT NULL,
  BOARD_SEQ number(11) NOT NULL,
  TITLE varchar2(200) NOT NULL,
  CONTENT mediumtext NULL,
  DISPLAY_F varchar2(1) DEFAULT 'Y' NOT NULL,
  REG_DATE date NOT NULL,
  REG_USER_SEQ number(11) NOT NULL,
  MOD_DATE date DEFAULT NULL,
  MOD_USER_SEQ number(11) DEFAULT NULL,
  DEL_DATE date DEFAULT NULL,
  PRIMARY KEY (SEQ),
  CONSTRAINT FN_BOARD_ARTICLE FOREIGN KEY (BOARD_SEQ) REFERENCES code_board_manager (SEQ)
);

CREATE SEQUENCE SEQ_BOARD_ARTICLE
    start with 1
    increment by 1
    nomaxvalue
    nocycle;

CREATE TABLE code_category (
  SEQ number(11) NOT NULL,
  BOARD_SEQ number(11) NOT NULL,
  TITLE varchar2(100) NOT NULL,
  USE_F varchar2(1) DEFAULT 'Y' NOT NULL,
  REG_DATE date DEFAULT SYSDATE NOT NULL,
  REG_USER_SEQ number(11) NOT NULL,
  MOD_DATE date DEFAULT NULL,
  MOD_USER_SEQ number(11) DEFAULT NULL,
  DEL_DATE date DEFAULT NULL,
  PRIMARY KEY (SEQ),
  CONSTRAINT FN_BOARD_CATE FOREIGN KEY (BOARD_SEQ) REFERENCES code_board_manager (SEQ)
);

CREATE SEQUENCE SEQ_CODE_CATEGORY
  INCREMENT BY 1 NOMAXVALUE NOCYCLE;

CREATE TABLE code_category_item (
  SEQ number(11) NOT NULL,
  CATEGORY_SEQ number(11) NOT NULL,
  TITLE varchar2(100) NOT NULL,
  REG_DATE date DEFAULT SYSDATE NOT NULL,
  REG_USER_SEQ number(11) NOT NULL,
  MOD_DATE date DEFAULT NULL,
  MOD_USER_SEQ number(11) DEFAULT NULL,
  DEL_DATE date DEFAULT NULL,
  PRIMARY KEY (SEQ),
  CONSTRAINT FN_CATE_ITEM FOREIGN KEY (CATEGORY_SEQ) REFERENCES code_category (SEQ)
);

CREATE SEQUENCE SEQ_CODE_CATEGORY
  INCREMENT BY 1 NOMAXVALUE NOCYCLE;

CREATE TABLE connect_category_article (
  ID number(11) NOT NULL,
  ARTICLE_SEQ number(11) NOT NULL,
  CATE_ITEM_SEQ number(11) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FN_CON_ARTICLE FOREIGN KEY (ARTICLE_SEQ) REFERENCES code_board_article (SEQ),
  CONSTRAINT FN_CON_CATE_ITEM FOREIGN KEY (CATE_ITEM_SEQ) REFERENCES code_category_item (SEQ)
);

CREATE TABLE member (
  SEQ number(11) NOT NULL,
  EMAIL varchar2(100) CONSTRAINT UQ_MEMBER_EMAIL UNIQUE NOT NULL ,
  PASSWORD varchar2(100) NOT NULL,
  NICK_NAME varchar2(100) NOT NULL,
  USER_TYPE varchar2(1) NOT NULL,
  REG_DATE date NOT NULL,
  MOD_DATE date DEFAULT NULL,
  MOD_USER_SEQ varchar2(50) DEFAULT NULL,
  DEL_DATE date DEFAULT NULL,
  PRIMARY KEY (SEQ)
);
